Deploy to s3
emergentworks/website pull request #62
Opened 2021-11-15 21:05 UTC by elleneub

Adds scripts to deploy to s3, and invalidate cloudfront cache

2021-11-17 16:59 UTC, markthom-as requested changes
This is awesome!!!!!
Left a few questions and suggestions for changes, but nothing that'd be blocking for deploy if you don't have the time to implement them.

Things you don't have the time to update I just ask that you create tickets for in the backlog so we can get them done in the future.

Great work!!!

2021-11-17 16:59 UTC, markthom-as commented on .github/workflows/github-actions-demo.yml
> +name: GitHub Actions Demo
I think we should change the YAML file name and action name from the defaults if possible

2021-11-17 16:59 UTC, markthom-as commented on README.md
> +  - To do this you may need to request those keys from an AWS admin
can we add "by emailing devops@emergentworks.org" please!

2021-11-17 16:59 UTC, markthom-as commented on deploy-website.sh
> +gatsby build
What happens here if the build fails? Does the script exit, or does it still delete the S3 files?
I think we want to make sure the script exits here on failure

2021-11-17 16:59 UTC, markthom-as commented on deploy-website.sh
> +aws s3 rm s3://emergentworks.org/ --recursive
We might want to check for the existence of "aws" here and send an explicit failure/exit signal here... Not sure how github actions will react in that case.

2021-11-17 16:59 UTC, markthom-as commented on package.json
> +    "update": "aws cloudfront create-invalidation --distribution-id E3NHW48S3W8DOR --paths '/*'",
I think moving this to a script with checks for the "aws" binary as mentioned above would be great. I think you could even have both of these scripts in the same shell file and have this one activated by a flag.

I think it's best practice as well to keep any of the specific values (s3 bucket URL, cloudfront distro ID) as variables (eventually env variables) at the top, to make the script more portable and easily updatable.

2021-11-23 17:30 UTC, elleneub commented on deploy-website.sh
> +gatsby build
switch to exit on failure, good call

2021-11-23 17:30 UTC, elleneub commented on package.json
> +    "update": "aws cloudfront create-invalidation --distribution-id E3NHW48S3W8DOR --paths '/*'",
moved and put environment vars in a .env file

2021-11-23 18:47 UTC, markthom-as approved these changes
LGTM, great work!

2021-11-23 21:08 UTC, merged