Separate About and Partner sections into two different pages
emergentworks/website pull request #64
Opened 2021-11-17 01:09 UTC by YusufBolden

Ran into a slight hiccup with MyQuer which Elle was able to guide me through. Pushed earlier but realized I didn't pull first, so I deleted that requests to save time from working through merge conflicts. There is some remaining whitespace at the bottom of the About page and we'll have to determine what to do with it. Also, the Partners page could use some additional content.

2021-11-17 01:10 UTC, YusufBolden commented
Spent several hours breaking the pages and fixing them to familiarize myself with the process

2021-11-17 15:31 UTC, elleneub requested changes
Looking really good! Couple things to work on but all in all quite good. the about.module.scss could probably have some styles deleted out of it as well now that it doesn't have the partners section

2021-11-17 15:31 UTC, elleneub commented on src/pages/partners.js
> +  //   })[0].childImageSharp.fluid
Want to remove this stuff about the team? Doesn't seem like we need it here.

2021-11-17 15:31 UTC, elleneub commented on src/pages/partners.module.scss
> +}
It'd be good to go through this and remove any styles that aren't being used in this section. We can talk if you'd like help figuring that out, the way it's happening in the project is kinda odd and took me quite a while to figure out.

2021-12-02 18:03 UTC, elleneub approved these changes
Looks great, well done!

2021-12-02 18:11 UTC, merged