Web 54 new careers page
emergentworks/website pull request #96
Opened 2022-02-23 19:52 UTC by YusufBolden

2022-02-23 20:15 UTC, ayreal requested changes
Great work @YusufBolden! I tested locally and the changes look good to me. Thanks for doing the formatting pass too.

I think it would also be nice to have a PR description that does the following:

1. Adds a link to the Jira issue
2. Briefly describes the change (although I think the PR title does this well enough in this case!)
3. Adds a screenshot

What do you think? Not necessary for approval because obviously we worked on this together, but I think it's a good habit to build for working in dev teams so that others who might be looking through the change history in the future have more context. 

Finally, here's long but great article about code review culture for your bathroom reading pleasure lol: https://mtlynch.io/code-review-love/

2022-02-23 20:15 UTC, ayreal commented on src/pages/careers.js
> +            </Button>
I noticed [this comment](https://docs.google.com/document/d/12A3hhyVKPUHQUaOysf8g0vClMMgkgqXGNLcffKH4OLU/edit?disco=AAAAUHhtYNc) Aedan wrote about making the open roles link more visually prominent. We don't have to do it in this PR, but I think it could be a good note to add to our design placeholder ticket!

2022-02-23 20:15 UTC, ayreal commented on src/pages/careers.js
> +              incarceration––by assembling a world-class community and team that
Super nitpicky, but let's use an emdash (—) here. I know it's hard to see, but we actually have two dashes (--), which you can see if you look at the webpage itself: 

![Image 2022-02-23 at 3 07 45 PM](https://user-images.githubusercontent.com/22643036/155399603-42ab8f10-7402-4d59-8c0e-2d7d1ca0717d.jpg)

2022-02-23 20:28 UTC, ayreal commented
Added #97 to prompt us to use some of these details in our PRs

2022-02-24 03:16 UTC, YusufBolden commented on src/pages/careers.js
> +              incarceration––by assembling a world-class community and team that
done. learned about endash and emdash because of this

2022-02-24 03:17 UTC, YusufBolden commented on src/pages/careers.js
> +            </Button>
So are you thinking to have the name of the role appear on the page as a link that opens up in greenhouse?

2022-02-24 15:05 UTC, ayreal commented on src/pages/careers.js
> +              incarceration––by assembling a world-class community and team that
Lolol right? The dash crew is well-represented in the world of unicode hahahah

2022-02-24 15:08 UTC, ayreal commented on src/pages/careers.js
> +            </Button>
This is a **great idea** that we could try later by playing around with Greenhouse's developer API! For now I think the link itself is fine for a v1. Maybe we just add a note to that design ticket to think about styling we could add that makes the link "pop" more 😉 !

2022-02-24 21:31 UTC, ayreal commented
@YusufBolden Looking good! Let's add a link to the Jira issue and maybe a screenshot to the description and get this puppy live!

2022-02-25 19:39 UTC, YusufBolden commented
Link to Jira ticket:

https://emergentworks.atlassian.net/browse/WEB-54?atlOrigin=eyJpIjoiOThkYjEzYjY5MjI3NDY5OTlhMDVkZTA2NWM5NmUzMDUiLCJwIjoiaiJ9

Screenshot of new Careers page:

<img width="1280" alt="Screen Shot 2022-02-25 at 2 36 01 PM" src="https://user-images.githubusercontent.com/61169982/155783968-a3a09112-7c38-40be-8d1c-781a3a6dc286.png">

2022-02-27 17:09 UTC, ayreal approved these changes
Thanks for adding this Yusuf! Some extra info -- if you want to update your description next time, here's how to do that:
![Image 2022-02-27 at 12 05 42 PM](https://user-images.githubusercontent.com/22643036/155892087-5385c029-bcdc-4d03-b427-77c00734600e.jpg)

It's nice to have a PR description because that's the first thing someone will look at if they're searching through a PR for historical context.

Woohoo, let's merge!

2022-02-28 05:09 UTC, merged